sudo: required
git:
  depth: 1
language: C
script: 
# Download, make and install SDL2-2.0.8 (stable)
  - |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install
  - cd code/code
  - make
  
